#!/bin/bash
###############################################################################
# Script name   : send_epfl_report.sh
#
# Author        : Sylvain Vuilleumier / Documentary engineering specialist
# Organization  : Digital repositories and archives - EPFL Library
# Contact       : sylvain.vuilleumier@epfl.ch
#
# Description  :
#   This script automates the monthly generation and email delivery of the
#   "EPFL Thesis Report".
#
#   It performs the following steps:
#     1. Activates the Python virtual environment (using the venv Python binary)
#     2. Executes the Python script create_records.py with its parameters
#     3. Checks for the presence of an error file (errors.log)
#     4. Sends an alert email with attachments if an error is detected
#     5. Verifies that the daily CSV report file has been generated
#     6. Sends the report by email to the standard recipient
#
#   If any problem occurs (Python script failure, missing file, detected error),
#   an alert email is automatically sent to the IT team with the relevant logs
#   attached.
#
# Dependencies :
#   - bash (>= 4)
#   - sendemail
#   - python3 (dedicated virtual environment)
#   - cron (monthly scheduled execution)
#
# Execution    :
#   - Manual:
#       ./send_epfl_report.sh
#
#   - Automated (cron, once per month):
#       30 6 1 * * /bin/bash /path/to/send_epfl_report.sh
#
# Logs         :
#   - run_YYYY-MM-DD.log : full execution log
#   - python.log        : Python script standard output
#   - errors.log        : generated by the Python script in case of error
#
# Security     :
#   - The script runs in strict Bash mode (set -Eeuo pipefail)
#   - All paths are dynamically resolved (BASE_DIR)
#   - No credentials are stored in plain text in this script
#
# Last update  : 2026-01-14
#
###############################################################################

set -Eeuo pipefail

# --- Encodage / locale ---
# Assure un encodage UTF-8 cohérent pour les accents dans les emails.
export LANG="${LANG:-C.UTF-8}"
export LC_ALL="${LC_ALL:-C.UTF-8}"

# --- Contexte d'exécution (pour les emails) ---
HOSTNAME_FQDN="$(hostname -f 2>/dev/null || hostname)"
SCRIPT_FULLPATH="$(realpath "$0")"

get_ini_value() {
  local section=$1 key=$2 file=$3
  awk -F' *= *' \
    "/^[[:space:]]*\\[$section\\][[:space:]]*$/{in_section=1;next}
     /^[[:space:]]*\\[/{in_section=0}
     in_section && \$1==\"$key\"{print \$2; exit}" "$file"
}

#BASE_DIR="/data/infoscience-thesis-to-alma"
BASE_DIR="$(dirname "$(realpath "$0")")"

# --- Virtualenv (à adapter) ---
VENV_DIR="$HOME/.virtualenvs/infoscience-thesis-to-alma"
PYTHON_BIN="$VENV_DIR/bin/python"

# --- Python script & config ---
PYTHON_SCRIPT="$BASE_DIR/create_records.py"
CONFIG_FILE="$BASE_DIR/config_sandbox.ini"
PYTHON_EXTRA_ARGS="$(get_ini_value bash python_extra_args "$CONFIG_FILE")"

# --- Mail ---
SMTP_SERVER="$(get_ini_value mail smtp_server "$CONFIG_FILE")"
FROM="$(get_ini_value mail from "$CONFIG_FILE")"
DEST_STANDARD="$(get_ini_value mail to_standard "$CONFIG_FILE")"
CC_STANDARD="$(get_ini_value mail cc_standard "$CONFIG_FILE")"
DEST_ERROR="$(get_ini_value mail to_error "$CONFIG_FILE")"

OUTPUT_DIR="$(get_ini_value report output_dir "$CONFIG_FILE")"
REPORT_PREFIX="$(get_ini_value general report_prefix "$CONFIG_FILE")"
FILENAME_TEMPLATE="$(get_ini_value report filename_template "$CONFIG_FILE")"

DATE="$(date +%Y-%m-%d)"
ATTACHMENT="$BASE_DIR/$OUTPUT_DIR/${REPORT_PREFIX}${DATE}.csv"

# --- Report ---
REPORT_DIR="$BASE_DIR/repports"
DATE="$(date +%Y-%m-%d)"
#ATTACHMENT="$REPORT_DIR/epfl_thesis_report_${DATE}.csv"
ATTACHMENT="$REPORT_DIR/${REPORT_PREFIX}${DATE}.csv"

# --- Logs ---
ERROR_FILE="$BASE_DIR/errors.log"
RUN_LOG="$BASE_DIR/run_${DATE}.log"

export PATH="/usr/bin:/bin"
exec > >(tee -a "$RUN_LOG") 2>&1

send_alert() {
  local subject="$1"
  local message="$2"

  local attachments=("$RUN_LOG")
  [ -f "$ERROR_FILE" ] && attachments+=("$ERROR_FILE")

  local attach_args=()
  for f in "${attachments[@]}"; do
    attach_args+=("-a" "$f")
  done

  if ! command -v sendemail >/dev/null 2>&1; then
    echo "❌ sendemail introuvable : impossible d'envoyer l'alerte."
    return 1
  fi

  sendemail \
    -f "$FROM" \
    -t "$DEST_ERROR" \
    -u "$subject" \
    -m "$message" \
    -o message-content-type=text/plain \
    -o message-charset=UTF-8 \
    "${attach_args[@]}" \
    -s "$SMTP_SERVER" \
    -v
}

die() {
  local msg="$1"
  echo "❌ $msg"
  send_alert "❌ EPFL: échec exécution (${DATE})" \
"Bonjour,

Le script EPFL a rencontré un problème :

$msg

Contexte d'exécution :
- Serveur : ${HOSTNAME_FQDN}
- Script  : ${SCRIPT_FULLPATH}

Merci de corriger le problème. Le run log est joint.
Si errors.log existe, il est également joint (à supprimer manuellement après résolution).

Cordialement,
Script automatique EPFL

---
Serveur : ${HOSTNAME_FQDN}
Script  : ${SCRIPT_FULLPATH}" || true
  exit 1
}

on_error() {
  local exit_code=$?
  local line_no=${BASH_LINENO[0]:-?}
  local cmd=${BASH_COMMAND:-?}
  die "Erreur (code $exit_code) à la ligne $line_no : $cmd"
}
trap on_error ERR

echo "=== Début: $(date -Is) ==="

# Pré-checks
command -v sendemail >/dev/null 2>&1 || die "sendemail introuvable (apt install sendemail)."
[ -x "$PYTHON_BIN" ] || die "Python du venv introuvable/non exécutable: $PYTHON_BIN"
[ -f "$PYTHON_SCRIPT" ] || die "Script Python introuvable: $PYTHON_SCRIPT"
[ -f "$CONFIG_FILE" ] || die "Config introuvable: $CONFIG_FILE"
[ -d "$REPORT_DIR" ] || die "Dossier rapports introuvable: $REPORT_DIR"

# Si errors.log existe déjà => alerte & stop
if [ -f "$ERROR_FILE" ]; then
  send_alert "❌ EPFL: errors.log déjà présent (${DATE})" \
"Bonjour,

Le fichier errors.log est déjà présent AVANT exécution.
Merci d'analyser et de supprimer ce fichier manuellement après résolution.

Aucun rapport n'a été envoyé.

Cordialement,
Script automatique EPFL

---
Serveur : ${HOSTNAME_FQDN}
Script  : ${SCRIPT_FULLPATH}" || true
  exit 0
fi

cd "$BASE_DIR"

# Exécution Python
echo "=== Lancement Python (venv) ==="
"$PYTHON_BIN" "$PYTHON_SCRIPT" --config-file "$CONFIG_FILE" $PYTHON_EXTRA_ARGS >> "$BASE_DIR/python.log" 2>&1
echo "=== Fin Python ==="

# errors.log créé => alerte & stop
if [ -f "$ERROR_FILE" ]; then
  send_alert "❌ EPFL: erreur pendant traitement (${DATE})" \
"Bonjour,

Une erreur a été détectée (errors.log généré). Voir la pièce jointe.
Merci de corriger puis de supprimer errors.log manuellement après résolution.

Aucun rapport n'a été envoyé.

Cordialement,
Script automatique EPFL

---
Serveur : ${HOSTNAME_FQDN}
Script  : ${SCRIPT_FULLPATH}" || true
  exit 0
fi

# --- Attente du fichier (max 30 secondes) ---
echo "⏳ Vérification de la génération du rapport..."
MAX_WAIT=30   # secondes
WAITED=0

while [ ! -f "$ATTACHMENT" ] && [ $WAITED -lt $MAX_WAIT ]; do
  sleep 2
  WAITED=$((WAITED + 2))
done
# Rapport manquant => alerte & stop
[ -f "$ATTACHMENT" ] || die "Rapport introuvable après attente (${MAX_WAIT}s) : $ATTACHMENT"

# Envoi rapport
sendemail \
  -f "$FROM" \
  -t "$DEST_STANDARD" \
  -cc "$CC_STANDARD" \
  -u "EPFL Thesis Report - ${DATE}" \
  -m "Bonjour,

Veuillez trouver en pièce jointe le rapport EPFL du ${DATE}.

Contexte d'exécution :
- Serveur : ${HOSTNAME_FQDN}
- Script  : ${SCRIPT_FULLPATH}

Cordialement,
EPFL" \
  -o message-content-type=text/plain \
  -o message-charset=UTF-8 \
  -a "$ATTACHMENT" \
  -s "$SMTP_SERVER" \
  -v

echo "✅ Rapport envoyé : $ATTACHMENT"
echo "=== Fin: $(date -Is) ==="
